### ISSUE TITLE
when I  run model.eval(), the output of model are float numbers instead of  integer numbers.

### ISSUE THREAD

**Issue by fireceW** [Felix-Petersen/difflogic#13]
![image](https://github.com/Felix-Petersen/difflogic/assets/113016024/aa9314d9-e304-4c8d-ba84-45287b6b8ce1)

when the mode is 'eval', I think the output of model should be integer numbers,However when I run  "model(x.to('cuda').round())" which in eval function, the output are float numbers.  I want to ask for some help.

**Comment by Felix-Petersen** [comment]
In eval mode, at the location that you indicate, it will be executed in float data type, but these floats should always be 0 or 1. It being in eval mode indicates that it will be discrete, i.e., 0/1 and discrete choices of logic gates.
