### ISSUE TITLE
Bug with `PackBitsTensor` class

### ISSUE THREAD

**Issue by mahdizaferanchi** [Felix-Petersen/difflogic#16]
When batch size isn't a multiple of `bit_count`, I'm pretty certain the result of `PackBitsTensor` is incorrect.

I trained a model on the monk dataset and the accuracy drops significantly when testing using `PackBitsTensor` for inference. I suspect the issue is less pronounced for higher dimensional data and could be missed.

I fixed this in my PR.

**Comment by Felix-Petersen** [comment]
Thanks for fixing the bug 🪲 and the addition of the `__repr__ `!
