### ISSUE TITLE
LogicTreeNet Architectur 

### ISSUE THREAD

**Issue by LexaNagiBator228** [Felix-Petersen/difflogic#27]
Thanks for amazing work!
Does `difflogic` already support LogicTreeNet? If not, when do you think it we be added?

**Comment by Felix-Petersen** [comment]
Thank you! I am currently preparing the major code release that will include convolutions, LogicTreeNet, and a variety of new optimizations, but I cannot give an exact timeline yet.

**Comment by b1shtream** [comment]
>Thank you! I am currently preparing the major code release that will include convolutions, LogicTreeNet, and a variety of new optimizations, but I cannot give an exact timeline yet.

Hi @Felix-Petersen 
Any updates on the above?? When can we expect to see the code. ??
