### ISSUE TITLE
Remove CUDA requirement

### ISSUE THREAD

**Issue by eloquentarduino** [Felix-Petersen/difflogic#4]
In the README you say that there is a Pytorch implementation and a CUDA implementation, which is faster. I don't have a GPU and I'm fine waiting a few minutes for the training to complete on the CPU. Is it possible to remove the CUDA requirement for installation if I only use the Python+CPU implementation?

**Comment by Felix-Petersen** [comment]
Thank you for reaching out.

Yes, it is possible to run it just from CPU with the PyTorch implementation. You would have to (1) download the repo locally, (2) remove the `import difflogic_cuda` statements, and (3) remove lines 2 and 28-32 from `setup.py`.

**Comment by eloquentarduino** [comment]
Thanks for the response. Since I want to write a tutorial on your library tailored to beginners who may not feel comfortable by applying these patches by themself, can 1) you release a cpu-only version of the library or 2) I fork the project and release such a cpu-only version?

**Comment by Felix-Petersen** [comment]
I created a branch `main-cpu`, where I also removed a bunch of components specific to the native CUDA implementation.

I made some basic testing and it should work now, but if you find any bugs, please tell me.

**Comment by eloquentarduino** [comment]
You're very supportive, thanks you. I'll test it this weekend

Il ven 21 apr 2023, 00:24 Felix Petersen ***@***.***> ha
scritto:

**Comment by HanXM715** [comment]
thank you
