### ISSUE TITLE
import difflogic_cuda

### ISSUE THREAD

**Issue by ZhaoZiyu1998** [Felix-Petersen/difflogic#5]
Hello.
I would like to re-produce the result and I have followed the readme file.
However, after I run the code, it said there is no module called difflogic_cuda.

I went over the source codes and I did not find any file with such name.

Any ideas?
![image](https://github.com/Felix-Petersen/difflogic/assets/20147679/b54983e6-a51f-4c7a-b31f-dab31a7031df)

**Comment by HanXM715** [comment]
+1

**Comment by HanXM715** [comment]
I also encountered a similar problem, how can I solve it
![image](https://github.com/Felix-Petersen/difflogic/assets/90486822/62d04363-9cde-4005-be9f-5f0c8f03abae)

**Comment by HanXM715** [comment]
@ZhaoZiyu1998 Hope to get your contact, thank you

**Comment by Felix-Petersen** [comment]
It seems like for this code, `import difflogic_cuda` was commented out. This is a dependency that gives access to the CUDA bindings for running on GPU. Could you specify whether you successfully installed the default package including CUDA (main branch or the git repo) / pip install difflogic?
