### ISSUE TITLE
Installation dependency package problem

### ISSUE THREAD

**Issue by HanXM715** [Felix-Petersen/difflogic#6]

**Comment by HanXM715** [comment]
The installation of difflogic depends on the packet error:
![image](https://github.com/Felix-Petersen/difflogic/assets/90486822/73816e2a-794f-4ad0-b8d5-939ede0715db)

**Comment by Felix-Petersen** [comment]
If you do not have an Nvidia GPU, please see the no-cuda branch (https://github.com/Felix-Petersen/difflogic/tree/main-cpu).

If you have a GPU, you need to set up CUDA and set the CUDA_HOME env variable.
